[package]
name = "schwimark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
rusqlite = "0.37.0"
toml = "0.9.2"
xdg = "3.0.0"
shlex = "1.3.0"
open = "5.3.2"
